# Generated by Django 5.0.1 on 2024-07-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_potholes', '0004_pothole_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pothole',
            name='discovery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del hallazgo'),
        ),
        migrations.AddField(
            model_name='pothole',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='pothole',
            name='municipality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='pothole',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Provincia'),
        ),
    ]
